### ISSUE TITLE
Viz Gallery

### ISSUE THREAD

**Issue by davemfish** [geointerest/msp_concierge_master#1]
The current plugin is a bit messy with ads and menus so we're looking for a cleaner, stripped down option that has the same functionality of tagging images, searching, etc.

http://rcharts.io/gallery/ -- this is the nicest looking example I've found. But it isn't just a simple plugin. Instead it's a bit of javascript, CSS, and a google spreadsheet that serves as the database of figures. Images need to be hosted somewhere with a URL that goes in the spreadsheet. Titles, authors, categories, tags, etc are all just fields in the spreadsheet.

The code is open here https://github.com/rcharts/gallery which was forked from here https://github.com/biovisualize/d3visualization

**Comment by davemfish** [comment]
This example turned out to be very easy to implement. I have a test version working locally with some figures hosted on our Seattle server. I'll add the html and js files to this repo so others can take a look and possibly integrate with the rest of the site.

**Comment by davemfish** [comment]
http://vulpes.sefs.uw.edu/d3visualization/gallery.html

here's the example I got working. I can add the files to this repository if given permission.

**Comment by geointerest** [comment]
Thanks, Dave.  D3 looks good.  You should have permission now.

Date: Mon, 5 Jan 2015 16:52:02 -0800

**Comment by davemfish** [comment]
I'm waiting to the upload code for this. It comes from a github repo which is open, but has no license specified. So I messaged the author to ask permission to use it.

**Comment by davemfish** [comment]
Based on wisdom from SW, I just went ahead and pushed the new files for the updated viz gallery. And edited the link to it in frame.html. So I think it should be 'live' now. All images in it are still just placeholders. I'll share the google spreadsheet that holds the references to the images.

**Comment by davemfish** [comment]
@woodsp

**Comment by davemfish** [comment]
@geointerest @woodsp, where's the best place to host images that appear the viz gallery? 

If they are already online somewhere, they don't need to move, just add URL to the google doc. But if someone wants to upload an offline image...for now I stashed the placeholder images on our vulpes server in Seattle.

**Comment by geointerest** [comment]
For now, in the "gallery" folder in the GitHub repo.  I'll update the links in the Google Doc once we get some more images up there.

Date: Wed, 14 Jan 2015 13:47:37 -0800

**Comment by geointerest** [comment]
Any idea why the gallery works fine on my local machine but not on the web?  It says looking for 'docs.google.com' but only the banner shows up when I do to http://geointerest.frih.org/msp/gallery.html.

Date: Wed, 14 Jan 2015 13:47:37 -0800

**Comment by davemfish** [comment]
It's something to do with "cross-origin requests":

`XMLHttpRequest cannot load https://docs.google.com/spreadsheets/d/1j_6Zqpp0H5m9nTjQemC-sq0I4gUbDvA5lH9Und7pK88/export?gid=0&format=csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://geointerest.frih.org' is therefore not allowed access.`

I believe a solution is to host the spreadsheet as a csv on the same server as hosts the other site files. I'll upload a csv to the repo and tell the JS to load it instead of the google doc. Then you could pull the repo to your hosting server and we'll see what happens.

**Comment by davemfish** [comment]
okay now gallery.html refers to a csv instead of a google doc. That is ./vizgallery/vizgallery_test.csv

Seems to work on my local webserver now. Try it out.

**Comment by geointerest** [comment]
Works.  Thanks!

Date: Wed, 14 Jan 2015 16:27:23 -0800

**Comment by geointerest** [comment]
Can we add a description to the viz gallery.  It looks and manages great, but without figure descriptions, viewers are going to be lost.
