### ISSUE TITLE
References - where to put them

### ISSUE THREAD

**Issue by davemfish** [geointerest/msp_concierge_master#4]
Lots of the new edits include in-line citations. So where is a good spot for the complete reference? Right now there are often references in the "Links" section of a page, but the links are not strictly references.

What about a dedicated References page that includes all the citations appearing anywhere on the site? 

Or what if the in-line citation is always a link to the actual article on the journal's site? If we do that do we even need the full reference listed on our site?

**Comment by davemfish** [comment]
Right now I've just got a separate text file going with any full references that were inserted in the Word doc edits.

**Comment by geointerest** [comment]
I think I fixed this.  Let's see what the beta testers say!
